### PR TITLE
[Node.js SDK] Update ChatConnector.js

### PR DESCRIPTION
**Pull request by rohankulkarni21**
Update ChatConnector.js to initiate conversation from skypeforbusiness.
In Start Conversation, received service URL from response was not used to send message to sip:user.
In postMessage, msg.address was getting deleted, but for posting message we need that address and conversation id in it.
Please include these changes.

### CODE REVIEW

**Comment by Stevenic** [comment]
I just made a fix to copy over the serviceUrl but the casing changes you did we don't want to take. If the case is truly wrong we need Skype to fix that. Can you verify that you actually see "Id" and "ServiceUrl" come back from skype, versus "id" and "serviceUrl"?

**Comment by rohankulkarni21** [comment]
Yes I did see Id instead of id for skypeforbusiness and ServiceUrl as well.

Did you take the delete changes as well?

Regards,
Rohan

On Sep 22, 2017 2:46 AM, Steven Ickman <notifications@github.com> wrote:

I just made a fix to copy over the serviceUrl but the casing changes you did we don't want to take. If the case is truly wrong we need Skype to fix that. Can you verify that you actually see "Id" and "ServiceUrl" come back from skype, versus "id" and "serviceUrl"?

**Comment by rohankulkarni21** [comment]
@Stevenic Please see attached screenshot showing the casing of Id and ServiceUrl which is returned from skypeforbusiness.
skyprforbusiness casing issue

**Comment by EricDahlvang** [comment]
Closing this PR because the code for this repository has been moved to https://github.com/Microsoft/BotBuilder-V3  If you think this PR is still relevant, please re-submit on the new repository.

**Pull request closed without merging**
