### PR TITLE
New locale (PT - Portuguese) for NodeJs BotBuilder

### PR DESCRIPTION
**Pull request by saveriopalmieri**
Hi Microsoft Team,

Just adding locale files for (PT) Portuguese language.

Cheers, Saverio.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@saveriopalmieri__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by saveriopalmieri** [comment]
Signed and submited.

**Comment by customcoops77** [comment]
I don't know what I'm doing.

**Comment by Stevenic** [comment]
Thanks

**Pull request merged**
