### PR TITLE
Merge Hub to Master

### PR DESCRIPTION
**Pull request by vishwacsena**
Has updated readme, specs. 
Snapshot of V3 is available in botbuilder-v3 branch as well as 3.0 branch in botbuilder.

### CODE REVIEW

**Comment by dandriscoll** [comment]
We have some PRs in flight right now. When did you want to complete this merge?

**Comment by vishwacsena** [comment]
@dandriscoll - EOD today is what we are tracking to wrap up all release activities. I'd like to see what we have merged by 5PM today .. we can continue to take PRs to master after that point .. does that work? If so, can you please help drive resolution on outstanding PRs going to Hub?

**Comment by tomlm** [comment]
I merged your changes in

**Comment by dandriscoll** [comment]
I'd like to get input from Dave, Savas, Todd -- let me see if they can review today

**Pull request merged**
