### PR TITLE
[Node.js SDK] Add next() and missing end() calls to ChatConnector

### PR DESCRIPTION
**Pull request by bilby91**
When using express or restify, in order to get the following handler to
execute, next function needs to be called.

### CODE REVIEW

**Comment by bilby91** [comment]
Any updates on merging this ?

**Comment by bilby91** [comment]
Any update?

**Comment by JasonSowers** [comment]
Will ping someone today from the node side.

**Comment by bilby91** [comment]
@Stevenic Sure, will double check! I doubt that there will be any issues based on conflicts. Will ping soone

**Comment by bilby91** [comment]
@Stevenic We are good to go now! Really nice to see our PRs going in :)

**Comment by JasonSowers** [comment]
@bilby91 we have time scheduled to review the Node PRs Wednesday

**Comment by harshithkashyap** [comment]
@bilby91 Since you are already ending the response with `res.end()`, could you share some info on why you are calling `next()`? 
The `next()` method calls further express middleware functions such as 404 error handler.
#3926 is related to this and we should move the middleware before the `app.post('/api/messages', connector.listen());`.

**Comment by bilby91** [comment]
@harshithkashyap Logging purposes. You want to call next so that a logging handler can capture all the information about the request + response in the logging message.

Make sense ?

**Pull request merged**
