### PR TITLE
[Node.js SDK] Improve ChatConnector request error text

### PR DESCRIPTION
**Pull request by santiagodoldan**
* Adds HTTP verb to the error message

### CODE REVIEW

**Comment by santiagodoldan** [comment]
It changes the message

**from**

`Request to \'https://smba.trafficmanager.net/client/v3/foo\' failed: [405] Method Not Allowed`

**to**

`POST to \'https://smba.trafficmanager.net/client/v3/foo\' failed: [405] Method Not Allowed`

**Comment by bilby91** [comment]
Any updates on this one ? Is really useful to know the HTTP verb!

**Comment by JasonSowers** [comment]
@bilby91 I'll follow up with this today

**Comment by JasonSowers** [comment]
@bilby91 @santiagodoldan  we have time scheduled to review the Node PRs Wednesday

**Pull request merged**
