### PR TITLE
[Node SDK] fixed the Sample code to use the UniversalBot Connector 

### PR DESCRIPTION
**Pull request by brijrajsingh**
Just fixed the sample nodejs code to use the UniversalBot Connector and Dialog at root / to respond with Hello world on a message

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@brijrajsingh__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (brsingh). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by Stevenic** [comment]
What prompted this change?

**Comment by brijrajsingh** [comment]
this is the Landing Readme.md for the Node Calling, while in rest of the documentation we have started using UniversalBot connector we didn't used the same in this document, any first time user won't be able to run the existing sample code as it is.

**Comment by Stevenic** [comment]
Thanks!

**Pull request merged**
