### PR TITLE
Fixing persian resources.

### PR DESCRIPTION
**Pull request by BehnamEmamian**
Hi Microsoft Developers

I am a Persian .Net developer. I have started to use Microsoft Bot Framework for developing a Telegram Bot.

It seems Persian resource has been translated by machine not human so I try to fix them. There are some mistakes and funny translations.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@BehnamEmamian__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by msft-shahins** [comment]
Thanks for your pull request. We use [Multilingual app toolkit](https://developer.microsoft.com/en-us/windows/develop/multilingual-app-toolkit) to generate localized resource s for bot builder. As a result all of the resource are generated from .xlf files. For example, you can find the Persian xlf here: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder/MultilingualResources/Microsoft.Bot.Builder.fa.xlf. It would be good if you can move your change to Microsoft.Bot.Builder.fa.xlf file, generate the resource file based on that (once you install multilingual app toolkit, building the bot builder project causes generation of updated resource files) and update your pull request.

**Comment by msft-shahins** [comment]
@BehnamEmamian have you had a chance to make changes based on my previous comment? I can take your changes and move them to the right xlf file if you want.

**Comment by BehnamEmamian** [comment]
I was busy this week, I think I can fix it this holiday.

**Comment by BehnamEmamian** [comment]
I like this tool, it is nice.

please have a look, it should be ok.

**Pull request merged**
