### PR TITLE
[Node SDK] Added German (de) locale for NodeJS BotBuilder

### PR DESCRIPTION
**Pull request by iMicknl**
- Added German (de) translation for the Node package
Thanks to Pim Steutel / Sarah Buckmann!

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@iMicknl__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@iMicknl__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@iMicknl__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (t-mivlee). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by iMicknl** [comment]
(Sorry for the close / reopen messages, something didn't work with the AZPRBOT. Solved now.)

**Comment by nwhitmont** [comment]
approved

**Comment by macrozone** [comment]
This hasn't been released to npm yet, has it?

**Pull request merged**
