### PR TITLE
[.NET SDK] Add JSONConverter to support builtin.datetimeV2.* LUIS entities

### PR DESCRIPTION
**Pull request by ejadib**
This PR is intended to fix issue #2764. 

FYI @msft-shahins @chrimc62

### CODE REVIEW

**Comment by willportnoy** [comment]
@ejadib there can be more than one meaningful item - can you update the pull request to deserialize all of them into a list of some type (e.g. IDictionary<string, object>)?

Is there a method to have newtonsoft deserialize JArray into List<T>?

**Comment by nwhitmont** [comment]
@ejadib Any updates on the LUIS datetime v2 progress?

**Comment by pcostantini** [comment]
Hi @willportnoy , @nwhitmont .
The PR is now updated to also resolve entity's resolution multiple values

image

Regards,
-PabloC.

**Comment by ejadib** [comment]
I created a set of extension methods to extract the values https://github.com/ejadib/LUIS-DateTimeV2-Extensions

**Pull request merged**
