### PR TITLE
[.NET SDK] Typo fixes in Samples: change instances of "Unkown" to "Unknown"

### PR DESCRIPTION
**Pull request by sphanley**

### CODE REVIEW

**Comment by sphanley** [comment]
How ironic that I've got a typo in the name of my branch!

**Comment by stevengum97** [comment]
Fixes same typos as #3482

**Comment by sphanley** [comment]
Whoops, I didn't realize someone else had caught this already. I noticed this independently while looking through the samples, but I should have searched deeper to see if it was a known issue!

**Comment by stevengum97** [comment]
Accepting this as @sphanley has already signed the CLA. Thanks for the contribution!

**Pull request merged**
