### PR TITLE
[Node.js SDK] Show buttons in MS Teams

### PR DESCRIPTION
**Pull request by santiagodoldan**

### CODE REVIEW

**Comment by santiagodoldan** [comment]
I put 5 because that's the number of buttons that MS Teams shows per message.

It's kind of annoying for users to mention the bot and then type `yes` or `no` each time a dialog uses a Confirm prompt, having `yes`/`no` buttons will make that UX much better IMO.

**Comment by santiagodoldan** [comment]
Any news here? Our bot is using this change in prod and so far is working good.

**Comment by santiagodoldan** [comment]
Any ideas if this can be merged?

**Comment by bilby91** [comment]
Any update?

**Comment by JasonSowers** [comment]
I'll ping someone today on the node side

**Comment by Stevenic** [comment]
Sorry for the delay

**Pull request merged**
