### PR TITLE
[C# SDK] Fix XML documentation, remove unused variable, proposing improvement for better mocking GetStateClient method.

### PR DESCRIPTION
**Pull request by andrejs-mamontovs**
Hi.
* Fix one error related to XML document (Xamarin Studio IDE);
* Fix unused variable warning;
* Proposing improvement for better testability (Moq);

### CODE REVIEW

**Comment by nwhitmont** [comment]
@andrejs-mamontovs can you provide a more specific PR title than "Small Improvements"? Describe the work you did so we can better understand your PR. thanks!

**Comment by andrejs-mamontovs** [comment]
Thanks a lot for the remark. Title fixed. Will keep in mind next time!

**Comment by willportnoy** [comment]
@andrejs-mamontovs we've removed Blog-CustomChannelData from the repository - are there other changes you want to preserve in this pull request?

**Comment by willportnoy** [comment]
I'm going to close this pull request for now, but feel free to ping us again.

**Pull request closed without merging**
